### ISSUE TITLE
Compilation on Raspberry 9 (stretch) fails

### ISSUE THREAD

**Issue by e-roux** [openhome/ohPlayer#10]
Compilation on Raspberry 9 (stretch) fails!

<pre>make -f Makefile.raspbian
make[1] : on entre dans le répertoire « /tmp/ohPlayer/ohPlayer/linux »
g++ -c -Wall -std=c++0x -I/usr/include/glib-2.0 -I/usr/lib/arm-linux-gnueabihf/glib-2.0/include -DTARG_ARCH=Linux-armhf -fstack-protector -fstack-check -I../dependencies/Linux-armhf/ohMediaPlayer/include -I../dependencies/Linux-armhf/ohNetmon/include -I../dependencies/Linux-armhf/openssl/include -I../dependencies/Linux-armhf/ohNetGenerated-Linux-armhf-Release/include/ohnet/OpenHome/Net/Core -I../dependencies/Linux-armhf/ohNet-Linux-armhf-Release/include/ohnet -c ConfigGTKKeyStore.cpp -o raspbian/objs/ConfigGTKKeyStore.o
g++ -c -Wall -std=c++0x -I/usr/include/glib-2.0 -I/usr/lib/arm-linux-gnueabihf/glib-2.0/include -DTARG_ARCH=Linux-armhf -fstack-protector -fstack-check -I../dependencies/Linux-armhf/ohMediaPlayer/include -I../dependencies/Linux-armhf/ohNetmon/include -I../dependencies/Linux-armhf/openssl/include -I../dependencies/Linux-armhf/ohNetGenerated-Linux-armhf-Release/include/ohnet/OpenHome/Net/Core -I../dependencies/Linux-armhf/ohNet-Linux-armhf-Release/include/ohnet -c RamStore.cpp -o raspbian/objs/RamStore.o
g++ -c -Wall -std=c++0x -I/usr/include/glib-2.0 -I/usr/lib/arm-linux-gnueabihf/glib-2.0/include -DTARG_ARCH=Linux-armhf -fstack-protector -fstack-check -I../dependencies/Linux-armhf/ohMediaPlayer/include -I../dependencies/Linux-armhf/ohNetmon/include -I../dependencies/Linux-armhf/openssl/include -I../dependencies/Linux-armhf/ohNetGenerated-Linux-armhf-Release/include/ohnet/OpenHome/Net/Core -I../dependencies/Linux-armhf/ohNet-Linux-armhf-Release/include/ohnet -c ControlPointProxy.cpp -o raspbian/objs/ControlPointProxy.o
g++ -c -Wall -std=c++0x -I/usr/include/glib-2.0 -I/usr/lib/arm-linux-gnueabihf/glib-2.0/include -DTARG_ARCH=Linux-armhf -fstack-protector -fstack-check -I../dependencies/Linux-armhf/ohMediaPlayer/include -I../dependencies/Linux-armhf/ohNetmon/include -I../dependencies/Linux-armhf/openssl/include -I../dependencies/Linux-armhf/ohNetGenerated-Linux-armhf-Release/include/ohnet/OpenHome/Net/Core -I../dependencies/Linux-armhf/ohNet-Linux-armhf-Release/include/ohnet -c Libav.cpp -o raspbian/objs/Libav.o
g++ -c -Wall -std=c++0x -I/usr/include/glib-2.0 -I/usr/lib/arm-linux-gnueabihf/glib-2.0/include -DTARG_ARCH=Linux-armhf -fstack-protector -fstack-check -I../dependencies/Linux-armhf/ohMediaPlayer/include -I../dependencies/Linux-armhf/ohNetmon/include -I../dependencies/Linux-armhf/openssl/include -I../dependencies/Linux-armhf/ohNetGenerated-Linux-armhf-Release/include/ohnet/OpenHome/Net/Core -I../dependencies/Linux-armhf/ohNet-Linux-armhf-Release/include/ohnet -c Volume.cpp -o raspbian/objs/Volume.o
g++ -c -Wall -std=c++0x -I/usr/include/glib-2.0 -I/usr/lib/arm-linux-gnueabihf/glib-2.0/include -DTARG_ARCH=Linux-armhf -fstack-protector -fstack-check -I../dependencies/Linux-armhf/ohMediaPlayer/include -I../dependencies/Linux-armhf/ohNetmon/include -I../dependencies/Linux-armhf/openssl/include -I../dependencies/Linux-armhf/ohNetGenerated-Linux-armhf-Release/include/ohnet/OpenHome/Net/Core -I../dependencies/Linux-armhf/ohNet-Linux-armhf-Release/include/ohnet -c ExampleMediaPlayer.cpp -o raspbian/objs/ExampleMediaPlayer.o
g++ -c -Wall -std=c++0x -I/usr/include/glib-2.0 -I/usr/lib/arm-linux-gnueabihf/glib-2.0/include -DTARG_ARCH=Linux-armhf -fstack-protector -fstack-check -I../dependencies/Linux-armhf/ohMediaPlayer/include -I../dependencies/Linux-armhf/ohNetmon/include -I../dependencies/Linux-armhf/openssl/include -I../dependencies/Linux-armhf/ohNetGenerated-Linux-armhf-Release/include/ohnet/OpenHome/Net/Core -I../dependencies/Linux-armhf/ohNet-Linux-armhf-Release/include/ohnet -c UpdateCheck.cpp -o raspbian/objs/UpdateCheck.o
g++ -c -Wall -std=c++0x -I/usr/include/glib-2.0 -I/usr/lib/arm-linux-gnueabihf/glib-2.0/include -DTARG_ARCH=Linux-armhf -fstack-protector -fstack-check -I../dependencies/Linux-armhf/ohMediaPlayer/include -I../dependencies/Linux-armhf/ohNetmon/include -I../dependencies/Linux-armhf/openssl/include -I../dependencies/Linux-armhf/ohNetGenerated-Linux-armhf-Release/include/ohnet/OpenHome/Net/Core -I../dependencies/Linux-armhf/ohNet-Linux-armhf-Release/include/ohnet -c MediaPlayerIF.cpp -o raspbian/objs/MediaPlayerIF.o
g++ -c -Wall -std=c++0x -I/usr/include/glib-2.0 -I/usr/lib/arm-linux-gnueabihf/glib-2.0/include -DTARG_ARCH=Linux-armhf -fstack-protector -fstack-check -I../dependencies/Linux-armhf/ohMediaPlayer/include -I../dependencies/Linux-armhf/ohNetmon/include -I../dependencies/Linux-armhf/openssl/include -I../dependencies/Linux-armhf/ohNetGenerated-Linux-armhf-Release/include/ohnet/OpenHome/Net/Core -I../dependencies/Linux-armhf/ohNet-Linux-armhf-Release/include/ohnet -c OpenHomePlayer.cpp -o raspbian/objs/OpenHomePlayer.o
g++ -c -Wall -std=c++0x -I/usr/include/glib-2.0 -I/usr/lib/arm-linux-gnueabihf/glib-2.0/include -DTARG_ARCH=Linux-armhf -fstack-protector -fstack-check -I../dependencies/Linux-armhf/ohMediaPlayer/include -I../dependencies/Linux-armhf/ohNetmon/include -I../dependencies/Linux-armhf/openssl/include -I../dependencies/Linux-armhf/ohNetGenerated-Linux-armhf-Release/include/ohnet/OpenHome/Net/Core -I../dependencies/Linux-armhf/ohNet-Linux-armhf-Release/include/ohnet -c DriverAlsa.cpp -o raspbian/objs/DriverAlsa.o
g++  raspbian/objs/ConfigGTKKeyStore.o  raspbian/objs/RamStore.o  raspbian/objs/ControlPointProxy.o  raspbian/objs/Libav.o  raspbian/objs/Volume.o  raspbian/objs/ExampleMediaPlayer.o  raspbian/objs/UpdateCheck.o  raspbian/objs/MediaPlayerIF.o  raspbian/objs/OpenHomePlayer.o  raspbian/objs/DriverAlsa.o -Wall -lglib-2.0 -lasound -lSourcePlaylist -lSourceSongcast -lSourceUpnpAv -lSourceRadio -lShell -lohMediaPlayer -lWebAppFramework -lConfigUi -lohNetGeneratedProxies -lohNetCore -lCodecAdts -lCodecAac -lCodecAacBase -lCodecMp3 -lCodecAifc -lCodecAlacApple -lCodecAlacAppleBase -lCodecPcm -lCodecAiff -lCodecAiffBase -lCodecVorbis -llibOgg -lCodecFlac -lCodecWav -lohPipeline -lpthread -lssl -lcrypto -ldl -lm -L../dependencies/Linux-armhf/ohMediaPlayer/lib -L../dependencies/Linux-armhf/ohNetmon/lib -L../dependencies/Linux-armhf/openssl/lib -L../dependencies/Linux-armhf/ohNet-Linux-armhf-Release/lib -L../dependencies/Linux-armhf/ohNetGenerated-Linux-armhf-Release/lib -o raspbian/openhome-player
../dependencies/Linux-armhf/ohMediaPlayer/lib/libConfigUi.a(ConfigUiMediaPlayer.cpp.84.o) : Dans la fonction « OpenHome::Web::ConfigAppMediaPlayer::ConfigAppMediaPlayer(OpenHome::Media::IInfoAggregator&, OpenHome::Environment&, OpenHome::Av::Product&, OpenHome::Configuration::IConfigManager&, OpenHome::Web::IConfigAppResourceHandlerFactory&, std::vector<OpenHome::Brx const*, std::allocator<OpenHome::Brx const*> > const&, OpenHome::Brx const&, OpenHome::Brx const&, unsigned int, unsigned int, OpenHome::Av::IRebootHandler&) » :
/home/hudson-zapp/workspace/ohMediaPlayer-Publish/PLATFORM/Linux-armhf/ohMediaPlayer/buildhudson/../OpenHome/Web/ConfigUi/ConfigUiMediaPlayer.cpp:32 : référence indéfinie vers « OpenHome::Av::Qobuz::kConfigKeySoundQuality »
collect2: error: ld returned 1 exit status
Makefile.raspbian:120 : la recette pour la cible « raspbian/openhome-player » a échouée
make[1]: *** [raspbian/openhome-player] Erreur 1
make[1] : on quitte le répertoire « /tmp/ohPlayer/ohPlayer/linux »
Makefile:28 : la recette pour la cible « raspbian » a échouée
make: *** [raspbian] Erreur 2
</pre>

The snippet used for compilation:
https://gist.github.com/gwin-zegal/0c844e46a46723b7860059750a0e4b9d#file-ohplayerbuild-sh

**Comment by seroper** [comment]
I get the same error, I tried building on Jessie, Stretch and Ubuntu.  Something is wrong with the dependency versions I think.  

Could someone with a working build environment please follow the readme instructions, build fresh and post back?

**Comment by e-roux** [comment]
Commit [ac200670ab5f05569dff9c9905c62a984afe7bb1](https://github.com/openhome/ohPlayer/commit/ac200670ab5f05569dff9c9905c62a984afe7bb1) fix the build. Thanks.
