### ISSUE TITLE
OpenHome/Private/Converter.h ->No such file or directory

### ISSUE THREAD

**Issue by BenMaticThings** [openhome/ohPlayer#13]
Hello,

I am trying install ohPlayer in ubuntu, however I got this error
"OpenHome/Private/Converter.h ->No such file or directory"
I cannot also find the Converter header file in your repository.

May I request if you could share the solution in this case.

Thanks,
Benson

**Comment by SimonChisholm** [comment]
You should get this by first cloning ohdevtools then running

./go fetch

from the ohPlayer directory to fetch binaries and headers for the upstream projects ohPlayer depends on.  This should fetch you headers for several projects, including ohNet, under the dependencies directory.

**Comment by BenMaticThings** [comment]
Thanks Simon! I got all the dependencies using above instructions 
However, I got new error bellow.. 
Your assistance in this matter would be greatly appreciated!


In file included from ../dependencies/Linux-x64/ohNet-Linux-x64-Release/include/ohnet/OpenHome/Private/Shell.h:7:0,
                 from ../dependencies/Linux-x64/ohNet-Linux-x64-Release/include/ohnet/OpenHome/Private/InfoProvider.h:5,
                 from ../dependencies/Linux-x64/ohMediaPlayer/include/OpenHome/Media/Pipeline/Msg.h:11,
                 from Volume.cpp:1:
../dependencies/Linux-x64/ohNet-Linux-x64-Release/include/ohnet/OpenHome/Private/Network.h:25:3: error: #error "Endianness must be defined."
 # error "Endianness must be defined."
   ^
Makefile.ubuntu:112: recipe for target 'ubuntu/objs/Volume.o' failed
make[1]: *** [ubuntu/objs/Volume.o] Error 1
make[1]: Leaving directory '/home/ben/lin/ohPlayer/linux'
Makefile:25: recipe for target 'ubuntu' failed
make: *** [ubuntu] Error 2
