### ISSUE TITLE
Compile Error

### ISSUE THREAD

**Issue by maosuyun2009** [openhome/ohPlayer#3]
I want to compile ohPlayer in my linux mint, But some error happend:
Libav.cpp:39:35: fatal error: libavutil/mathematics.h: No such file or directory

I think this code:
extern "C"
{
# include "libavutil/mathematics.h"
# include "libavutil/opt.h"
# include "libavutil/samplefmt.h"
# include "libavformat/avformat.h"
# include "libavresample/avresample.h"

}
shold put into #ifdef USE_LIBAVCODEC

After I have compiled success, I run openhome-player, segment fault happened:
Using Subnet 192.168.0.0
ZoneHandler.  SenderZone is PiPlayer-dennis-Inspiron-7447
OHM SENDER DRIVER LATENCY 150
Segmentation fault

openhome-player must run in ubuntu? my system is linux min 17

**Comment by pedropoulis** [comment]
Thanks - we'll fix that in the next revision.

The linux-based ohPlayer has been developed/tested on Ubuntu 12.x/14.x.
The code uses libav (optionally for native codec support), libnotify and gtk and should be largely compatible with other debian-based distros, but Ubuntu has been the development target in this first revision.

Do you have any more info on the segfault cause/location ?

**Comment by Alzinho** [comment]
The compile issue has now been resolved.
